version: '3.8'

services:
  gifex-front:
    build: ./
    container_name: gifex-front
    expose:
      - 3000
    volumes:
      - ./:/usr/src/app
    #ports:
    #  - 80:3000
    restart: always
    networks:
      -proxy
networks:
  proxy:
    external: true